import 'bootstrap/dist/css/bootstrap.css'
import Head from "next/head";

function User({users}) {
    return (
        <div>
            <Head>
                <title>Users</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <h1>Users</h1>
            <table className="table">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Full Name</th>
                    <th scope="col">username</th>
                    <th scope="col">Email</th>
                </tr>
                </thead>
                <tbody>
                {users.map((user) => (
                    <tr>
                        <td>{user.id}</td>
                        <td>{user.name}</td>
                        <td>{user.username}</td>
                        <td>{user.email}</td>
                    </tr>
                ))}
                </tbody>
            </table>
        </div>
    )
}

// This function gets called at build time
export async function getStaticProps() {
    // Call an external API endpoint to get posts
    const res = await fetch('https://jsonplaceholder.typicode.com/users')
    const users = await res.json()

    // By returning { props: { users } }, the Blog component
    // will receive `users` as a prop at build time
    return {
        props: {
            users,
        },
    }
}

export default User